２回目の再生時に、最初からループ開始点まで飛んでしまう不具合を修正
tokineco/GameHelper2dx pull request #7
Opened 2016-11-01 07:43 UTC by shinhirota

フラグ isLoopInterval が正しく初期化されていないので、表題のような現象が発生します。

とりあえず playBgm の最後にフラグを初期化するようにしたら、現象は解消しました。

（※最後の１行に無意味な差分が出てしまっていますが、無害です。すみません。）

2016-11-01 14:54 UTC, tokineco commented on AudioManager.cpp
> +    if (_bgmLoopList.count(_bgmFileName) > 0) {
プルリクをいただいたにもかからずスミマセン。_bgmFileNameだとBGMが流れていない場合に空となりスルーされます。_bgmFileNameにセットした後か、playBgmの引数であるbaseNameにすることで意図した動作となります。

`if (_bgmLoopList.count(baseName) > 0) {`

2016-11-01 14:54 UTC, tokineco commented on AudioManager.cpp
> +        _bgmLoopList[_bgmFileName].isLoopInterval = false;
`    _bgmLoopList[baseName].isLoopInterval = false;`

2016-11-01 14:57 UTC, tokineco requested changes
プルリクをいただいたにもかからずスミマセン。_bgmFileNameだとBGMが流れていない場合に空となりスルーされます。_bgmFileNameにセットした後か、playBgmの引数baseNameにすることで意図した動作となります。

2016-11-02 00:52 UTC, shinhirota commented
失礼しました。
コードを貼り付ける場所を間違えていました・・・。

こちらで試したコードは、

    _bgmFileName = baseName;

の行の後に、今回の修正をいれていたのですが、この行の前に修正いれてプルリクエストしてしまいました。
これだとご指摘の通りですね。

2016-11-02 15:18 UTC, merged